// Generated by scripts/proposal-driver.js . do not edit by hand.
// Firm: Wolf Builders & Joiners Ltd
// Generated: 2026-04-27T10:51:26.912Z

'use client';

import { useEffect } from 'react';

const STYLE_CSS = `
*, *::before, *::after { margin: 0; padding: 0; box-sizing: border-box; }
:root {
  --bg-deep: #030303;
  --bg-card: rgba(8,18,12,0.72);
  --border: rgba(125,196,160,0.16);
  --border-accent: rgba(77,224,130,0.30);
  --accent: #4DE082;
  --accent-blue: #00A755;
  --accent-glow: #7df3aa;
  --accent-green: #10b981;
  --accent-green-glow: #72f3bf;
  --accent-amber: #f59e0b;
  --accent-amber-glow: #fcd34d;
  --accent-red: #ef4444;
  --text-primary: rgba(255,255,255,0.94);
  --text-secondary: rgba(255,255,255,0.62);
  --text-muted: rgba(255,255,255,0.36);
}
html, body { height: 100%; overflow: hidden; font-family: 'Inter', -apple-system, sans-serif; background: var(--bg-deep); color: var(--text-primary); -webkit-font-smoothing: antialiased; text-rendering: optimizeLegibility; }
::selection { background: rgba(77,224,130,0.3); }

#particles { position: fixed; inset: 0; z-index: 0; }
.bg-gradient { position: fixed; inset: 0; z-index: 1; pointer-events: none; background: radial-gradient(ellipse at 20% 0%, rgba(77,224,130,0.07) 0%, transparent 50%), radial-gradient(ellipse at 80% 100%, rgba(0,167,85,0.06) 0%, transparent 50%), radial-gradient(ellipse at 50% 50%, rgba(0,0,0,0.4) 0%, transparent 100%); }
.bg-grid { position: fixed; inset: 0; z-index: 2; pointer-events: none; background-image: linear-gradient(rgba(77,224,130,0.04) 1px, transparent 1px), linear-gradient(90deg, rgba(77,224,130,0.04) 1px, transparent 1px); background-size: 48px 48px; mask-image: radial-gradient(ellipse at center, rgba(0,0,0,0.3) 0%, transparent 70%); }

.slideshow { position: relative; z-index: 10; width: 100vw; height: 100vh; }
.slide { position: absolute; inset: 0; display: flex; align-items: center; justify-content: center; padding: clamp(20px, 3vw, 56px); padding-top: clamp(60px, 8vh, 80px); padding-bottom: clamp(60px, 8vh, 80px); opacity: 0; transform: translateY(28px) scale(0.97); transition: opacity 0.55s cubic-bezier(.4,0,.2,1), transform 0.55s cubic-bezier(.4,0,.2,1); pointer-events: none; flex-direction: column; overflow-y: auto; -webkit-overflow-scrolling: touch; }
.slide.active { opacity: 1; transform: translateY(0) scale(1); pointer-events: auto; }
.slide.exit-up { opacity: 0; transform: translateY(-28px) scale(0.97); }
.slide-inner { width: min(92vw, 1100px); text-align: center; }

.slide-label { display: inline-flex; align-items: center; gap: 8px; font: 600 11px/1 'JetBrains Mono', monospace; letter-spacing: 0.22em; text-transform: uppercase; color: var(--accent); margin-bottom: 18px; }
.slide-label::before { content: ''; width: 8px; height: 2px; background: var(--accent); border-radius: 1px; }
.slide-title { font-family: 'Playfair Display', serif; font-size: clamp(26px, 4.5vw, 60px); font-weight: 700; letter-spacing: -0.04em; line-height: 1.08; margin-bottom: 16px; }
.slide-title span, .gradient-text { background: linear-gradient(90deg, var(--accent-blue), var(--accent), #a8f0c4); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
.slide-subtitle { font: 500 11px/1.6 'JetBrains Mono', monospace; letter-spacing: 0.16em; text-transform: uppercase; color: var(--text-muted); margin-bottom: 28px; }
.slide-body { font-size: clamp(14px, 1.6vw, 18px); color: var(--text-secondary); line-height: 1.7; max-width: 820px; margin: 0 auto; }
.slide-body strong { color: var(--text-primary); font-weight: 600; }
.slide-body em { color: var(--accent-glow); font-style: normal; font-weight: 500; }

.cards-grid { display: grid; gap: 14px; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); margin-top: 24px; text-align: left; }
.card { background: linear-gradient(180deg, rgba(8,18,12,0.78), rgba(5,12,8,0.88)); border: 1px solid var(--border); border-radius: 18px; padding: clamp(16px, 2vw, 24px); backdrop-filter: blur(12px); transition: border-color 0.3s, box-shadow 0.3s; position: relative; overflow: hidden; }
.card::before { content: ''; position: absolute; inset: 0; background: linear-gradient(135deg, rgba(255,255,255,0.02), transparent 30%, transparent 70%, rgba(77,224,130,0.04)); pointer-events: none; }
.card:hover { border-color: var(--border-accent); box-shadow: 0 0 30px rgba(77,224,130,0.08); }
.card-label { font: 600 10px/1 'JetBrains Mono', monospace; letter-spacing: 0.2em; text-transform: uppercase; color: var(--accent); margin-bottom: 8px; display: flex; align-items: center; gap: 8px; }
.card-label::before { content: ''; width: 6px; height: 6px; border-radius: 50%; background: var(--accent); box-shadow: 0 0 10px rgba(77,224,130,0.6); }
.card h3 { font-family: 'Playfair Display', serif; font-size: clamp(15px, 1.6vw, 20px); font-weight: 700; letter-spacing: -0.03em; margin-bottom: 8px; }
.card p, .card li { font-size: clamp(12px, 1.1vw, 14px); color: var(--text-secondary); line-height: 1.6; }
.card ul { list-style: none; padding: 0; }
.card ul li { position: relative; padding-left: 16px; margin-bottom: 5px; }
.card ul li::before { content: ''; position: absolute; left: 0; top: 8px; width: 5px; height: 5px; border-radius: 50%; background: rgba(77,224,130,0.5); }
.card ul li strong { color: var(--text-primary); }
.card ul li em { color: var(--accent-glow); font-style: normal; }

.glass-box { background: rgba(8,18,12,0.7); border: 1px solid var(--border); border-radius: 18px; padding: clamp(18px, 2.5vw, 28px); backdrop-filter: blur(16px); text-align: left; position: relative; overflow: hidden; }
.glass-box::before { content: ''; position: absolute; inset: 0; background: linear-gradient(135deg, rgba(255,255,255,0.03), transparent 40%); pointer-events: none; }

.stats-row { display: flex; justify-content: center; gap: clamp(20px, 4vw, 56px); margin-top: 28px; flex-wrap: wrap; }
.stat { text-align: center; }
.stat-value { font-family: 'Playfair Display', serif; font-size: clamp(28px, 4.5vw, 52px); font-weight: 700; line-height: 1; background: linear-gradient(90deg, var(--accent-blue), var(--accent)); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
.stat-label { font: 500 10px/1 'JetBrains Mono', monospace; letter-spacing: 0.2em; text-transform: uppercase; color: var(--text-muted); margin-top: 8px; }

.pill { display: inline-flex; align-items: center; gap: 7px; padding: 7px 16px; border-radius: 999px; font: 600 10px/1 'JetBrains Mono', monospace; letter-spacing: 0.12em; text-transform: uppercase; margin: 4px; }
.pill.green { background: rgba(77,224,130,0.08); border: 1px solid rgba(77,224,130,0.25); color: var(--accent-glow); }

.two-col { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; text-align: left; margin-top: 24px; }

.timeline { margin-top: 24px; text-align: left; max-width: 800px; margin-left: auto; margin-right: auto; }
.timeline-item { display: flex; gap: 18px; margin-bottom: 16px; position: relative; }
.timeline-dot { width: 12px; height: 12px; border-radius: 50%; background: var(--accent); flex-shrink: 0; margin-top: 5px; box-shadow: 0 0 12px rgba(77,224,130,0.4); position: relative; }
.timeline-item:not(:last-child) .timeline-dot::after { content: ''; position: absolute; left: 50%; top: 12px; width: 1px; height: calc(100% + 12px); background: linear-gradient(to bottom, rgba(77,224,130,0.3), transparent); transform: translateX(-50%); }
.timeline-content h4 { font: 600 11px/1 'JetBrains Mono', monospace; letter-spacing: 0.14em; text-transform: uppercase; color: var(--accent-glow); margin-bottom: 5px; }
.timeline-content p { font-size: clamp(13px, 1.2vw, 15px); color: var(--text-secondary); line-height: 1.6; }
.timeline-content p strong { color: var(--text-primary); }

.proposal-card { background: linear-gradient(180deg, rgba(8,18,12,0.82), rgba(5,12,8,0.92)); border: 1px solid var(--border-accent); border-radius: 20px; padding: clamp(20px, 2.5vw, 32px); backdrop-filter: blur(14px); text-align: left; position: relative; overflow: hidden; max-width: 720px; margin: 28px auto 0; }
.proposal-card::before { content: ''; position: absolute; top: 0; left: 0; right: 0; height: 1px; background: linear-gradient(90deg, transparent, var(--accent), transparent); }
.proposal-card h3 { font-family: 'Playfair Display', serif; font-size: clamp(18px, 2vw, 26px); font-weight: 700; letter-spacing: -0.03em; margin-bottom: 14px; }
.proposal-card .deliverables { list-style: none; padding: 0; margin-bottom: 20px; }
.proposal-card .deliverables li { position: relative; padding-left: 20px; margin-bottom: 8px; font-size: clamp(13px, 1.2vw, 15px); color: var(--text-secondary); line-height: 1.6; }
.proposal-card .deliverables li::before { content: ''; position: absolute; left: 0; top: 8px; width: 6px; height: 6px; border-radius: 50%; background: var(--accent); }
.proposal-card .deliverables li strong { color: var(--text-primary); }
.proposal-card .pricing { display: flex; gap: 24px; padding: 16px 20px; background: rgba(77,224,130,0.05); border: 1px solid rgba(77,224,130,0.18); border-radius: 12px; flex-wrap: wrap; }
.proposal-card .pricing .price-block { text-align: center; flex: 1; }
.proposal-card .pricing .price-label { font: 500 9px/1 'JetBrains Mono', monospace; letter-spacing: 0.16em; text-transform: uppercase; color: var(--text-muted); margin-bottom: 6px; }
.proposal-card .pricing .price-value { font-family: 'Playfair Display', serif; font-size: clamp(22px, 2.5vw, 32px); font-weight: 700; }
.proposal-card .pricing .price-value.one-time { color: var(--text-primary); }
.proposal-card .pricing .price-value.recurring { background: linear-gradient(90deg, var(--accent-blue), var(--accent)); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
.proposal-card .tagline { font-family: 'Playfair Display', serif; font-size: clamp(13px, 1.2vw, 16px); font-style: italic; color: var(--text-muted); margin-top: 14px; padding-top: 14px; border-top: 1px solid var(--border); text-align: center; }

.cta-row { display: flex; gap: 12px; justify-content: center; flex-wrap: wrap; margin-top: 28px; }
.cta-btn { display: inline-flex; align-items: center; gap: 8px; padding: 14px 22px; border-radius: 12px; font: 600 12px/1 'JetBrains Mono', monospace; letter-spacing: 0.14em; text-transform: uppercase; text-decoration: none; transition: all 0.2s; }
.cta-btn.primary { background: linear-gradient(180deg, rgba(77,224,130,0.18), rgba(0,167,85,0.18)); border: 1px solid var(--border-accent); color: var(--accent-glow); box-shadow: 0 0 30px rgba(77,224,130,0.12); }
.cta-btn.primary:hover { box-shadow: 0 0 40px rgba(77,224,130,0.24); border-color: var(--accent); }
.cta-btn.ghost { background: rgba(8,18,12,0.6); border: 1px solid var(--border); color: var(--text-secondary); }
.cta-btn.ghost:hover { border-color: var(--border-accent); color: var(--text-primary); }

.brand-header { position: fixed; top: 18px; left: 24px; z-index: 100; display: flex; align-items: center; gap: 10px; }
.brand-name { font-family: 'Playfair Display', serif; font-size: 14px; font-weight: 700; letter-spacing: -0.02em; }
.confidential-pill { position: fixed; top: 20px; right: 24px; z-index: 100; display: inline-flex; align-items: center; gap: 7px; padding: 6px 14px; border-radius: 999px; background: rgba(77,224,130,0.06); border: 1px solid rgba(77,224,130,0.2); font: 500 10px/1 'JetBrains Mono', monospace; letter-spacing: 0.14em; text-transform: uppercase; color: var(--accent-glow); }
.confidential-pill::before { content: ''; width: 6px; height: 6px; border-radius: 50%; background: var(--accent); box-shadow: 0 0 10px rgba(77,224,130,0.6); animation: pulse 2s ease-in-out infinite; }
@keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.4; } }

.progress-bar { position: fixed; top: 0; left: 0; height: 2px; z-index: 200; background: linear-gradient(90deg, var(--accent-blue), var(--accent)); transition: width 0.4s cubic-bezier(.4,0,.2,1); box-shadow: 0 0 10px rgba(77,224,130,0.4); }

.nav-bar { position: fixed; bottom: 20px; left: 50%; transform: translateX(-50%); z-index: 100; display: flex; align-items: center; gap: 14px; padding: 10px 18px; border-radius: 999px; background: rgba(8,18,12,0.88); border: 1px solid var(--border); backdrop-filter: blur(16px); }
.nav-btn { width: 34px; height: 34px; border-radius: 50%; background: rgba(77,224,130,0.08); border: 1px solid rgba(77,224,130,0.22); color: var(--accent); cursor: pointer; display: flex; align-items: center; justify-content: center; transition: all 0.2s; font-size: 13px; }
.nav-btn:hover { background: rgba(77,224,130,0.18); border-color: var(--accent); }
.nav-counter { font: 500 11px/1 'JetBrains Mono', monospace; letter-spacing: 0.14em; color: var(--text-muted); min-width: 56px; text-align: center; }

.council-strip { position: fixed; bottom: 78px; left: 50%; transform: translateX(-50%); z-index: 99; max-width: min(92vw, 720px); padding: 10px 16px; border-radius: 12px; background: rgba(8,18,12,0.85); border: 1px solid var(--border); backdrop-filter: blur(12px); font-size: 12px; color: var(--text-secondary); line-height: 1.5; }
.council-strip strong { color: var(--accent-glow); font-weight: 600; }

@media (max-width: 768px) {
  .two-col, .cards-grid { grid-template-columns: 1fr; }
  .stats-row { gap: 14px; }
  .proposal-card .pricing { flex-direction: column; gap: 12px; }
  .brand-name { display: none; }
  .confidential-pill { font-size: 9px; padding: 5px 10px; }
  .council-strip { display: none; }
}
`;

const HTML_BODY = `
<canvas id="particles"></canvas>
<div class="bg-gradient"></div>
<div class="bg-grid"></div>

<div class="brand-header">
  <span class="brand-name" style="color:var(--accent-glow);">Sovereign Bookings</span>
</div>

<div class="confidential-pill">Confidential</div>
<div class="progress-bar" id="progressBar"></div>

<div class="slideshow" id="slideshow">

<div class="slide active" data-slide="1"><div class="slide-inner">
  <div class="slide-label">Sovereign Bookings</div>
  <h1 class="slide-title">A Bookings Engine for<br><span>Wolf Builders &amp; Joiners Ltd</span></h1>
  <p class="slide-subtitle" style="margin-top:12px;">Prepared for Wolf Builders</p>
  <p class="slide-subtitle" style="color:var(--text-muted);letter-spacing:0.2em;">April 2026 &middot; Manchester, Cheshire, Stockport, Bolton &amp; North West</p>
  <p style="margin-top:28px;font:500 11px/1 'JetBrains Mono',monospace;letter-spacing:0.14em;color:var(--text-muted);">Presented by Miller Glenholmes</p>
  <p style="margin-top:18px;font:500 11px/1.5 'JetBrains Mono',monospace;letter-spacing:0.14em;color:var(--accent-glow);max-width:560px;margin-left:auto;margin-right:auto;">&pound;500 setup &nbsp;&middot;&nbsp; &pound;300 per qualified appointment &nbsp;&middot;&nbsp; free website</p>
</div></div>

<div class="slide" data-slide="2"><div class="slide-inner">
  <div class="slide-label">01 &middot; Diagnosis</div>
  <h1 class="slide-title">Right Now, You're<br><span>Leaving Quotes On The Table</span></h1>
  <p class="slide-body">A homeowner in Manchester, Cheshire, Stockport, Bolton &amp; North West Googles Wolf Builders ready to spend on a garden room. They land on your site and the journey to a booked quote is broken before it starts.</p>
  <p class="slide-body" style="margin-top:14px;"><em>Slow load. Mobile-only contact (07931). Garden rooms is item 6 of 10 in a generic builder service list, no dedicated funnel.</em></p>

  <div class="stats-row" style="margin-top:36px;">
    <div class="stat"><div class="stat-value">78%</div><div class="stat-label">Judge credibility by website</div></div>
    <div class="stat"><div class="stat-value">&lt;3s</div><div class="stat-label">Time to form a judgment</div></div>
    <div class="stat"><div class="stat-value">94%</div><div class="stat-label">First impressions are design</div></div>
  </div>

  <div class="glass-box" style="margin-top:32px;text-align:center;border-color:var(--border-accent);max-width:760px;margin-left:auto;margin-right:auto;">
    <p style="font-size:clamp(14px,1.4vw,17px);color:var(--text-secondary);line-height:1.7;">Right now your enquiries are <strong style="color:var(--text-primary);">window shoppers</strong>. We turn them into <em style="color:var(--accent-glow);font-style:normal;font-weight:600;">qualified appointments</em> in your calendar.</p>
  </div>
</div></div>

<div class="slide" data-slide="3"><div class="slide-inner">
  <div class="slide-label">02 &middot; Solution</div>
  <h1 class="slide-title">A Free Site, <span>Booked Appointments</span></h1>
  <p class="slide-body">We build you a dedicated garden room site. We run the ads. We qualify the homeowners. <strong>You only pay for the ones that show up to quote.</strong></p>

  <div class="two-col" style="margin-top:28px;">
    <div class="card">
      <div class="card-label">What We Build</div>
      <h3>Garden Room site, your branding</h3>
      <ul style="margin-top:10px;">
        <li>Home Offices</li>
<li>Garden Studios</li>
<li>Garden Rooms</li>
<li>Home Gyms</li>
<li>Garage Conversions</li>
<li>Bespoke Extensions</li>
        <li><strong>Lead capture form</strong> wired to SMS + email</li>
        <li>Calendar booking with reminders</li>
        <li>Mobile-first, fast loading</li>
      </ul>
    </div>
    <div class="card">
      <div class="card-label">What We Run</div>
      <h3>The whole bookings engine</h3>
      <ul style="margin-top:10px;">
        <li><strong>Facebook + Instagram ads</strong> targeted at Manchester, Cheshire, Stockport, Bolton &amp; North West</li>
        <li>SMS, email and phone follow-up</li>
        <li>Qualification: budget, area, decision-maker</li>
        <li>Slot booked into your diary, not just a form fill</li>
      </ul>
    </div>
  </div>

  <div class="glass-box" style="margin-top:28px;text-align:center;border-color:var(--border-accent);max-width:720px;margin-left:auto;margin-right:auto;">
    <p style="font-size:clamp(13px,1.3vw,16px);color:var(--text-secondary);line-height:1.7;">One garden room install at &pound;25k pays back the setup fee plus <strong style="color:var(--accent-glow);">30 qualified appointments</strong>. The maths works on the very first close.</p>
  </div>
</div></div>

<div class="slide" data-slide="4"><div class="slide-inner">
  <div class="slide-label">03 &middot; How It Works</div>
  <h1 class="slide-title">Four Steps. <span>You Show Up And Quote.</span></h1>

  <div class="timeline" style="margin-top:32px;">
    <div class="timeline-item"><div class="timeline-dot"></div><div class="timeline-content">
      <h4>01. We build your site and launch your ads</h4>
      <p>Your dedicated garden room site goes live alongside targeted Facebook and Instagram ads. We handle design, copy and creative. <strong>You approve, we launch.</strong></p>
    </div></div>
    <div class="timeline-item"><div class="timeline-dot"></div><div class="timeline-content">
      <h4>02. Homeowners request quotes</h4>
      <p>Real homeowners in Manchester, Cheshire, Stockport, Bolton &amp; North West land on your site and request a quote. <strong>No window shoppers, no time wasters.</strong> People with gardens, budgets, intent.</p>
    </div></div>
    <div class="timeline-item"><div class="timeline-dot"></div><div class="timeline-content">
      <h4>03. We qualify and book them into your calendar</h4>
      <p>Our system follows up by SMS, email and phone. <strong>Decision-maker confirmed, real budget, real project</strong> before they ever hit your diary.</p>
    </div></div>
    <div class="timeline-item"><div class="timeline-dot"></div><div class="timeline-content">
      <h4>04. You turn up, quote, we invoice &pound;300 per show</h4>
      <p>Drive to the property, quote the job, do what you do best. <strong>We invoice &pound;300 per qualified appointment</strong> that confirmed and showed up. No show, no pay.</p>
    </div></div>
  </div>
</div></div>

<div class="slide" data-slide="5"><div class="slide-inner">
  <div class="slide-label">04 &middot; Guarantee</div>
  <h1 class="slide-title">10 Qualified Appointments<br><span>In 30 Days. On Us If Not.</span></h1>
  <p class="slide-body"><strong>Active delivery</strong> means from the day your first ad goes live. Typically day 7-10 from signing.</p>

  <div class="two-col" style="margin-top:28px;">
    <div class="card">
      <div class="card-label">Qualified means</div>
      <h3>Real homeowner, real intent</h3>
      <ul style="margin-top:10px;">
        <li>Homeowner in Manchester, Cheshire, Stockport, Bolton &amp; North West</li>
        <li>Decision-maker present at the appointment</li>
        <li>Budget fits the projects you typically take</li>
        <li><strong>Actually showed up</strong> at the agreed slot</li>
      </ul>
    </div>
    <div class="card">
      <div class="card-label">If we miss</div>
      <h3>Free work until we hit ten</h3>
      <ul style="margin-top:10px;">
        <li>Miller covers ad creative and management</li>
        <li>You still pay Meta ad spend and the &pound;300 per show</li>
        <li>60-day cap from go-live, clock pauses for client delays</li>
        <li>If the cap expires you keep the site, full migration support</li>
      </ul>
    </div>
  </div>

  <p style="margin-top:18px;font:500 10px/1 'JetBrains Mono',monospace;letter-spacing:0.14em;text-transform:uppercase;color:var(--text-muted);text-align:center;">No-shows and renters disqualified. Full terms at sovereignbookings.co.uk/guarantee.</p>
</div></div>

<div class="slide" data-slide="6"><div class="slide-inner">
  <div class="slide-label">05 &middot; The Numbers</div>
  <h1 class="slide-title">Pay-Per-Appointment. <span>No Retainer.</span></h1>

  <div class="proposal-card">
    <h3>Your offer, Wolf Builders</h3>
    <ul class="deliverables">
      <li><strong>Free dedicated garden room site</strong>, custom-coded, live in 1-2 weeks</li>
      <li>Lead capture, SMS + email follow-up, calendar booking</li>
      <li>Facebook and Instagram ad campaign managed end-to-end</li>
      <li>Qualification calls before anything hits your diary</li>
      <li><strong>10-bookings-in-30-days guarantee</strong>, 60-day cap</li>
      <li>No retainer. We revisit at month 3 if you want more.</li>
    </ul>
    <div class="pricing">
      <div class="price-block">
        <div class="price-label">Setup</div>
        <div class="price-value one-time">&pound;500</div>
      </div>
      <div class="price-block">
        <div class="price-label">Per qualified appointment</div>
        <div class="price-value recurring">&pound;300</div>
      </div>
      <div class="price-block">
        <div class="price-label">Website</div>
        <div class="price-value one-time" style="color:var(--accent-glow);">FREE</div>
      </div>
    </div>
    <p class="tagline">No show, no charge. We only get paid when you do.</p>
  </div>

  <p style="margin-top:18px;font:500 10px/1 'JetBrains Mono',monospace;letter-spacing:0.14em;text-transform:uppercase;color:var(--text-muted);text-align:center;">
    Ad spend is &pound;25-30/day to Meta directly. We never touch your card.
  </p>
</div></div>

<div class="slide" data-slide="7"><div class="slide-inner">
  <h1 class="slide-title" style="font-size:clamp(28px,4.8vw,64px);">Ready when <span>you are, Wolf Builders</span></h1>
  <p class="slide-body" style="margin-top:18px;">Pick a 15-minute slot. We walk through your area, your usual project size, and the first week of campaign creative. No obligation.</p>

  <div class="cta-row">
    <a class="cta-btn primary" href="https://sovereignbookings.co.uk/book-call" target="_blank" rel="noopener">Book a 15-min call &rarr;</a>
    <a class="cta-btn ghost" href="https://wa.me/447986767758?text=Hi%20Sovereign%20Bookings%20%E2%80%93%20I%20saw%20my%20proposal%20at%20sovereignsystem.co.uk%2Fproposal-pitch%2Fwolf-builders" target="_blank" rel="noopener">WhatsApp Miller</a>
  </div>

  <div style="margin-top:40px;">
    <div class="slide-label" style="margin-bottom:8px;">Sovereign Bookings</div>
    <p style="font:500 11px/1.8 'JetBrains Mono',monospace;letter-spacing:0.16em;text-transform:uppercase;color:var(--text-muted);">Booked-in garden room quotes &middot; North West England</p>
    <p style="margin-top:12px;font:400 10px/1.7 'JetBrains Mono',monospace;letter-spacing:0.14em;text-transform:uppercase;color:var(--text-muted);">April 2026 &middot; Confidential &middot; info@wolfbuilders.co.uk</p>
  </div>
</div></div>
</div>

<div class="nav-bar" id="navBar">
  <button class="nav-btn" id="prevBtn" aria-label="Previous slide">&larr;</button>
  <span class="nav-counter" id="navCounter">1 / 7</span>
  <button class="nav-btn" id="nextBtn" aria-label="Next slide">&rarr;</button>
</div>


`;

const SCRIPT_BODY = `
(function() {
  var canvas = document.getElementById('particles');
  if (!canvas) return;
  var ctx = canvas.getContext('2d');
  var COLOR = '#4DE082';
  var w, h, particles, mouse, dpr;

  function Particle() { this.reset(true); }
  Particle.prototype.reset = function(initial) {
    this.x = Math.random() * w;
    this.y = Math.random() * h;
    this.vx = 0; this.vy = 0;
    this.age = initial ? Math.random() * 200 : 0;
    this.life = Math.random() * 200 + 100;
  };
  Particle.prototype.update = function() {
    var angle = (Math.cos(this.x * 0.005) + Math.sin(this.y * 0.005)) * Math.PI;
    this.vx += Math.cos(angle) * 0.15;
    this.vy += Math.sin(angle) * 0.15;
    var dx = mouse.x - this.x, dy = mouse.y - this.y;
    var dist = Math.sqrt(dx * dx + dy * dy);
    if (dist < 140) {
      var force = (140 - dist) / 140;
      this.vx -= dx * force * 0.04;
      this.vy -= dy * force * 0.04;
    }
    this.x += this.vx; this.y += this.vy;
    this.vx *= 0.95; this.vy *= 0.95;
    this.age++;
    if (this.age > this.life) this.reset(false);
    if (this.x < 0) this.x = w; if (this.x > w) this.x = 0;
    if (this.y < 0) this.y = h; if (this.y > h) this.y = 0;
  };
  Particle.prototype.draw = function() {
    var alpha = 1 - Math.abs((this.age / this.life) - 0.5) * 2;
    ctx.globalAlpha = alpha * 0.8;
    ctx.fillStyle = COLOR;
    ctx.fillRect(this.x, this.y, 1.5, 1.5);
  };

  function initParticles() {
    dpr = window.devicePixelRatio || 1;
    w = window.innerWidth; h = window.innerHeight;
    canvas.width = w * dpr; canvas.height = h * dpr;
    canvas.style.width = w + 'px'; canvas.style.height = h + 'px';
    ctx.scale(dpr, dpr);
    var count = w < 480 ? 40 : w < 768 ? 60 : 300;
    particles = [];
    for (var i = 0; i < count; i++) particles.push(new Particle());
    mouse = { x: -1000, y: -1000 };
  }
  function animate() {
    ctx.globalAlpha = 1;
    ctx.fillStyle = 'rgba(3,3,3,0.1)';
    ctx.fillRect(0, 0, w, h);
    for (var i = 0; i < particles.length; i++) { particles[i].update(); particles[i].draw(); }
    requestAnimationFrame(animate);
  }

  window.addEventListener('resize', function() { ctx.setTransform(1, 0, 0, 1, 0, 0); initParticles(); });
  window.addEventListener('mousemove', function(e) { mouse.x = e.clientX; mouse.y = e.clientY; });
  window.addEventListener('mouseleave', function() { mouse.x = -1000; mouse.y = -1000; });
  initParticles();
  animate();

  var slides = document.querySelectorAll('.slide');
  var total = slides.length;
  var current = 0;
  var isTransitioning = false;
  var progressBar = document.getElementById('progressBar');
  var navCounter = document.getElementById('navCounter');
  var prevBtn = document.getElementById('prevBtn');
  var nextBtn = document.getElementById('nextBtn');

  function updateProgress() {
    progressBar.style.width = ((current + 1) / total * 100) + '%';
    navCounter.textContent = (current + 1) + ' / ' + total;
  }
  function goTo(index) {
    if (isTransitioning || index === current || index < 0 || index >= total) return;
    isTransitioning = true;
    var direction = index > current ? 'exit-up' : '';
    slides[current].classList.remove('active');
    if (direction) slides[current].classList.add(direction);
    slides[index].classList.remove('exit-up');
    slides[index].classList.add('active');
    slides[index].scrollTop = 0;
    current = index;
    updateProgress();
    setTimeout(function() {
      slides.forEach(function(s) { if (!s.classList.contains('active')) s.classList.remove('exit-up'); });
      isTransitioning = false;
    }, 560);
  }
  function next() { goTo(current + 1); }
  function prev() { goTo(current - 1); }

  document.addEventListener('keydown', function(e) {
    if (e.key === 'ArrowRight' || e.key === ' ') { e.preventDefault(); next(); }
    if (e.key === 'ArrowLeft') { e.preventDefault(); prev(); }
  });
  prevBtn.addEventListener('click', prev);
  nextBtn.addEventListener('click', next);

  var touchStartX = 0, touchStartY = 0, touchStartTime = 0;
  document.addEventListener('touchstart', function(e) {
    touchStartX = e.changedTouches[0].clientX;
    touchStartY = e.changedTouches[0].clientY;
    touchStartTime = Date.now();
  }, { passive: true });
  document.addEventListener('touchend', function(e) {
    var dx = e.changedTouches[0].clientX - touchStartX;
    var dy = e.changedTouches[0].clientY - touchStartY;
    var dt = Date.now() - touchStartTime;
    if (Math.abs(dx) > 50 && Math.abs(dx) > Math.abs(dy) * 1.5 && dt < 500) {
      dx < 0 ? next() : prev();
    }
  }, { passive: true });

  var wheelTimeout;
  document.addEventListener('wheel', function(e) {
    var activeSlide = slides[current];
    var isScrollable = activeSlide.scrollHeight > activeSlide.clientHeight;
    var atTop = activeSlide.scrollTop <= 0;
    var atBottom = activeSlide.scrollTop + activeSlide.clientHeight >= activeSlide.scrollHeight - 2;
    if (isScrollable && !atTop && !atBottom) return;
    if (isScrollable && e.deltaY < 0 && !atTop) return;
    if (isScrollable && e.deltaY > 0 && !atBottom) return;
    clearTimeout(wheelTimeout);
    wheelTimeout = setTimeout(function() {
      if (e.deltaY > 0) next();
      else if (e.deltaY < 0) prev();
    }, 80);
  }, { passive: true });

  updateProgress();
})();
`;

export default function ProposalPage() {
  useEffect(() => {
    if (typeof window === 'undefined') return;
    try {
      const fn = new Function(SCRIPT_BODY);
      fn();
    } catch (err) {
      console.error('Proposal slideshow init failed:', err);
    }
  }, []);

  return (
    <>
      <title>{"Sovereign Bookings . Proposal: Wolf Builders & Joiners Ltd"}</title>
      <meta name="robots" content="noindex, nofollow" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      <link
        href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;600&family=Playfair+Display:wght@600;700;800&display=swap"
        rel="stylesheet"
      />
      <style dangerouslySetInnerHTML={{ __html: STYLE_CSS }} />
      <div dangerouslySetInnerHTML={{ __html: HTML_BODY }} />
    </>
  );
}
